### ISSUE TITLE
cannot compile it for esp8266

### ISSUE THREAD

**Issue by benzman** [dannerph/esphome_vitoconnect#1]
I have a problem to compile your example for the nodemcuv2 esp8266. I get an error:

`src/main.cpp:283:74: error: expected '{' before '<' token
  283 |   sensor_lambdafilter = new sensor::LambdaFilter([=](float x) -> optional<float> {
      |   `

I don't know where to look for the error. Can you help?

**Comment by dannerph** [comment]
Hi @benzman 
it seems that the ESP8266 platform has issues with the lambda filter for custom components. I quickly tested a workaround by using the multiply filter instead of a lambda filter. Check the updated readme for this fix. I only tested the compile process, please report back, if the fix is working for you.

**Comment by benzman** [comment]
Thanks  a lot! it works now. Also had to disable the logger, because it uses the same serial port - so I set
`logger:
  baud_rate: 0`
